// Generated by CoffeeScript 1.8.0
(function() {
  var app, consumer_key, express, pocket;

  express = require('express');

  pocket = require('../index');

  consumer_key = '33618-33e802fbfa7f47fc172bd91b';

  pocket.init(consumer_key, 'http://127.0.0.1:4000/pocket/callback');

  app = express();

  app.use(require('cookie-parser')());

  app.use(pocket.oauth());

  app.get('/', function(req, res) {
    return res.redirect('/pocket/authorize');
  });

  app.get('/items', function(req, res) {
    var token;
    token = req.cookies['access_token'];
    if (!token) {
      return res.json([]);
    }
    return pocket.get({
      access_token: token,
      state: 'unread'
    }, function(err, ret) {
      return res.json(err || ret);
    });
  });

  app.listen(4000);

  console.log('VISIT http://127.0.0.1:4000/');

}).call(this);
