// Generated by CoffeeScript 1.6.3
(function() {
  var Pocket, extend, makeUrl, pocket, qs, request;

  qs = require('qs');

  request = require('request');

  Pocket = (function() {
    Pocket.prototype.apiHost = 'https://getpocket.com';

    Pocket.prototype.requestTokenUri = '/v3/oauth/request';

    Pocket.prototype.authorizeUri = '/auth/authorize';

    Pocket.prototype.accessTokenUri = '/v3/oauth/authorize';

    Pocket.prototype.retrieveUri = '/v3/get';

    Pocket.prototype.addUri = '/v3/add';

    Pocket.prototype.modifyUri = '/v3/send';

    function Pocket(consumer_key, redirect_uri) {
      this.consumer_key = consumer_key;
      this.redirect_uri = redirect_uri;
    }

    Pocket.prototype.getUrl = function(apiType) {
      return "" + this.apiHost + this["" + apiType + "Uri"];
    };

    Pocket.prototype.getRequestTokenUrl = function() {
      return this.getUrl("requestToken");
    };

    Pocket.prototype.getAuthorizeUrl = function() {
      return this.getUrl("authorize");
    };

    Pocket.prototype.getAccessTokenUrl = function() {
      return this.getUrl("accessToken");
    };

    Pocket.prototype.get = function(conditions, callback) {
      var url;
      if (conditions == null) {
        conditions = {};
      }
      if (callback == null) {
        callback = function() {};
      }
      if (typeof conditions === 'function') {
        callback = conditions;
        conditions = {};
      }
      conditions.consumer_key = this.consumer_key;
      if (!conditions.access_token) {
        throw new Error("access_token is required");
      }
      url = makeUrl(this.getUrl('retrieve'), conditions);
      return request.get(url, function(err, resp, ret) {
        var e;
        try {
          return callback(err, JSON.parse(ret));
        } catch (_error) {
          e = _error;
          return callback(err, ret);
        }
      });
    };

    Pocket.prototype.add = function(data, callback) {
      if (data == null) {
        data = {};
      }
      if (callback == null) {
        callback = function() {};
      }
      data.consumer_key = this.consumer_key;
      return request.post({
        headers: {
          'content-type': 'application/x-www-form-urlencoded'
        },
        url: this.getUrl('add'),
        body: qs.stringify(data)
      }, function(err, resp, ret) {
        var e;
        try {
          return callback(err, JSON.parse(ret));
        } catch (_error) {
          e = _error;
          console.error(err, ret);
          return callback(null, {});
        }
      });
    };

    Pocket.prototype.send = function(data, callback) {
      var access_token, actions, url;
      if (callback == null) {
        callback = function() {};
      }
      actions = data.actions, access_token = data.access_token;
      url = makeUrl(this.getUrl('modify'), {
        consumer_key: this.consumer_key,
        access_token: access_token
      });
      url += '&actions=' + encodeURIComponent(JSON.stringify(actions));
      return request.get(url, function(err, resp, ret) {
        var e;
        try {
          return callback(err, JSON.parse(ret));
        } catch (_error) {
          e = _error;
          console.error(err, ret);
          return callback(null, {});
        }
      });
    };

    return Pocket;

  })();

  makeUrl = function(prefix, query) {
    if (typeof query !== 'string') {
      query = qs.stringify(query);
    }
    return "" + prefix + "?" + query;
  };

  extend = function(a, b) {
    var key, val;
    for (key in b) {
      val = b[key];
      a[key] = val;
    }
    return a;
  };

  pocket = new Pocket;

  pocket.Pocket = Pocket;

  pocket.init = function(consumer_key, redirect_uri) {
    if (!consumer_key) {
      throw new Error("consumer_key is required");
    }
    pocket.consumer_key = consumer_key;
    return pocket.redirect_uri = redirect_uri;
  };

  module.exports = pocket;

}).call(this);
